# -*- coding: utf-8 -*-
"""Fetching Abstract

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxjEi839iSjpseI1AHidzcizlGaL4VpO
"""

pip install requests bibtexparser

import bibtexparser
import requests
import time
import re

# ==========================================
# CONFIGURATION
# ==========================================
API_KEY = ""

INPUT_FILE = "/content/pop_results.bibtex"
OUTPUT_FILE = "/content/resolved_results.bib"

HEADERS = {"x-api-key": API_KEY}

# OpenAlex and Crossref tolerate fast polling (their polite pools are
# ~5-10 req/sec), so this can be short. Semantic Scholar is the slow one --
# it's now queried LAST, only when the faster sources fail, so its strict
# limit no longer taxes every single entry.
SLEEP_SECONDS = 1.0
MAX_RETRIES = 4

# Crossref asks that you identify yourself via a 'mailto' in the User-Agent
# or as a query param -- this puts you in their "polite pool" with much
# higher and more reliable rate limits. Put a real email here.
CROSSREF_MAILTO = ""
CROSSREF_HEADERS = {"User-Agent": f"abstract-backfill-script (mailto:{CROSSREF_MAILTO})"}

# OpenAlex does NOT use API keys -- it uses the same "polite pool" pattern as
# Crossref: identify yourself via mailto for higher/more reliable rate limits.
# Free, no signup. Reuse the same email as above.
OPENALEX_MAILTO = CROSSREF_MAILTO

# CORE does use a real API key. Get one free at core.ac.uk/services/api
# ROTATE the key you paste here before sharing this script with anyone --
# treat it as compromised if it's ever appeared in a chat, doc, or repo.
CORE_API_KEY = ""
CORE_HEADERS = {"Authorization": f"Bearer {CORE_API_KEY}"}


def clean_text(text):
    if not text:
        return ""
    text = text.replace('{', '').replace('}', '').replace('\n', ' ')
    return re.sub(r'\s+', ' ', text).strip()


def clean_crossref_abstract(raw):
    """
    Crossref wraps abstracts in JATS XML, e.g. <jats:p>...</jats:p>,
    sometimes with nested tags and a leading 'Abstract' label. Strip tags
    and normalize whitespace.
    """
    if not raw:
        return None
    text = re.sub(r'<[^>]+>', ' ', raw)  # strip all XML/HTML tags
    text = re.sub(r'\s+', ' ', text).strip()
    # Crossref often prefixes the literal word "Abstract"
    text = re.sub(r'^Abstract\.?\s*', '', text, flags=re.IGNORECASE)
    return text if text else None


def api_get(url, params=None, headers=None):
    """
    Wraps requests.get with retry-on-429 and verbose error reporting.
    Returns (status_code, json_or_none, error_message_or_none)
    """
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.get(url, params=params, headers=headers, timeout=15)
        except requests.exceptions.RequestException as e:
            return None, None, f"Network error: {e}"

        if resp.status_code == 200:
            try:
                return 200, resp.json(), None
            except ValueError:
                return 200, None, "200 OK but response was not valid JSON"

        if resp.status_code == 429:
            wait = 5 * attempt
            print(f"      [429 rate-limited] retrying in {wait}s (attempt {attempt}/{MAX_RETRIES})...")
            time.sleep(wait)
            continue

        # Any other non-200: surface it immediately, don't retry
        return resp.status_code, None, f"HTTP {resp.status_code}: {resp.text[:200]}"

    return 429, None, "Gave up after repeated 429 rate-limiting"


def fetch_paper_by_id(paper_id, log):
    """
    The canonical /paper/{id} endpoint reliably returns the abstract.
    The /match and /search endpoints often return abstract: null for the
    SAME paper even when one exists -- their result projection is a lighter
    index than the full paper record. So once we have a paperId, always
    do one more hop here before giving up.
    """
    fields = "title,abstract,tldr"
    url = f"https://api.semanticscholar.org/graph/v1/paper/{paper_id}"
    status, data, err = api_get(url, params={"fields": fields}, headers=HEADERS)
    if err:
        log.append(f"  -> full-record lookup error: {err}")
        return None
    if data:
        if data.get('abstract'):
            return data['abstract']
        if data.get('tldr') and data['tldr'].get('text'):
            return "[TLDR] " + data['tldr']['text']
        log.append("  -> full-record lookup confirmed: genuinely no abstract/tldr for this paper")
    return None


def reconstruct_openalex_abstract(inverted_index):
    """
    OpenAlex stores abstracts as {word: [position1, position2, ...]} to
    avoid copyright issues with redistributing full text. Reconstruct the
    plain-text abstract from word positions.
    """
    if not inverted_index:
        return None
    position_map = {}
    for word, positions in inverted_index.items():
        for pos in positions:
            position_map[pos] = word
    if not position_map:
        return None
    ordered = [position_map[i] for i in sorted(position_map.keys())]
    return " ".join(ordered)


def fetch_from_openalex(doi, title, log):
    """
    Free, no API key -- identify via mailto for the polite pool (much
    higher rate limit, ~10 req/sec vs ~1 req/sec without it). Good
    coverage for conference papers that Crossref/S2 often miss.
    """
    params_common = {"mailto": OPENALEX_MAILTO}

    if doi:
        url = f"https://api.openalex.org/works/https://doi.org/{doi}"
        status, data, err = api_get(url, params=params_common, headers=None)
        if err:
            log.append(f"OpenAlex DOI lookup error: {err}")
        elif data:
            abstract = reconstruct_openalex_abstract(data.get('abstract_inverted_index'))
            if abstract:
                return abstract
            log.append("OpenAlex DOI matched but no abstract_inverted_index present")

    if title:
        url = "https://api.openalex.org/works"
        params = {**params_common, "search": title, "per_page": 1}
        status, data, err = api_get(url, params=params, headers=None)
        if err:
            log.append(f"OpenAlex title search error: {err}")
        elif data:
            results = data.get('results', [])
            if results:
                abstract = reconstruct_openalex_abstract(results[0].get('abstract_inverted_index'))
                if abstract:
                    return abstract
                log.append("OpenAlex title search found a record but no abstract_inverted_index")
            else:
                log.append("OpenAlex title search returned no candidates")

    return None


def fetch_from_core(doi, title, log):
    """
    Fallback source #3. Good for open-access conference papers (IEEE/ACM
    preprints, institutional repositories) that Crossref/OpenAlex/S2 miss.
    Requires a free API key from core.ac.uk/services/api.
    """
    if doi:
        url = "https://api.core.ac.uk/v3/search/works"
        params = {"q": f'doi:"{doi}"', "limit": 1}
        status, data, err = api_get(url, params=params, headers=CORE_HEADERS)
        if err:
            log.append(f"CORE DOI search error: {err}")
        elif data:
            results = data.get('results', [])
            if results and results[0].get('abstract'):
                return clean_text(results[0]['abstract'])
            if results:
                log.append("CORE DOI matched but record has no abstract field")
            else:
                log.append("CORE DOI search returned no candidates")

    if title:
        url = "https://api.core.ac.uk/v3/search/works"
        params = {"q": f'title:"{title}"', "limit": 1}
        status, data, err = api_get(url, params=params, headers=CORE_HEADERS)
        if err:
            log.append(f"CORE title search error: {err}")
        elif data:
            results = data.get('results', [])
            if results and results[0].get('abstract'):
                return clean_text(results[0]['abstract'])
            if results:
                log.append("CORE title search found a record but no abstract field")
            else:
                log.append("CORE title search returned no candidates")

    return None


def fetch_from_crossref(doi, title, log):
    """
    Fallback source. No API key needed, generous rate limit in the 'polite
    pool' (just identify yourself via CROSSREF_MAILTO above). Crossref's
    abstract coverage differs from Semantic Scholar's -- mostly strong for
    journal articles with registered abstracts, weaker for conference papers.
    Returns plain-text abstract or None.
    """
    # Priority: DOI lookup is exact and fast
    if doi:
        url = f"https://api.crossref.org/works/{doi}"
        status, data, err = api_get(url, params=None, headers=CROSSREF_HEADERS)
        if err:
            log.append(f"Crossref DOI lookup error: {err}")
        elif data:
            msg = data.get('message', {})
            abstract = clean_crossref_abstract(msg.get('abstract'))
            if abstract:
                return abstract
            log.append("Crossref DOI matched but record has no abstract field")

    # Fallback: title search (bibliographic query), take top hit
    if title:
        url = "https://api.crossref.org/works"
        params = {"query.bibliographic": title, "rows": 1}
        status, data, err = api_get(url, params=params, headers=CROSSREF_HEADERS)
        if err:
            log.append(f"Crossref title search error: {err}")
        elif data:
            items = data.get('message', {}).get('items', [])
            if items:
                top = items[0]
                abstract = clean_crossref_abstract(top.get('abstract'))
                if abstract:
                    return abstract
                log.append("Crossref title search found a record but it has no abstract field")
            else:
                log.append("Crossref title search returned no candidates")

    return None


def fetch_full_abstract(doi, title):
    doi = clean_text(doi)
    title = clean_text(title)
    log = []

    # Priority 1: OpenAlex -- no key, ~10 req/sec polite pool, strong general coverage
    oa_abstract = fetch_from_openalex(doi, title, log)
    if oa_abstract:
        return oa_abstract, "OpenAlex", log
    time.sleep(SLEEP_SECONDS)

    # Priority 2: Crossref -- no key, generous polite pool, strong DOI coverage
    cr_abstract = fetch_from_crossref(doi, title, log)
    if cr_abstract:
        return cr_abstract, "Crossref", log
    time.sleep(SLEEP_SECONDS)

    # Priority 3: CORE -- keyed, good for open-access conference papers
    core_abstract = fetch_from_core(doi, title, log)
    if core_abstract:
        return core_abstract, "CORE", log
    time.sleep(SLEEP_SECONDS)

    # Priority 4 (last, slowest): Semantic Scholar -- strict unauthenticated-tier
    # rate limit makes this the most expensive source to query, so it only
    # runs once everything faster has already failed. Still worth trying:
    # it sometimes has TLDR summaries or abstracts the others lack.
    fields = "title,abstract,tldr,paperId"

    if doi:
        url = f"https://api.semanticscholar.org/graph/v1/paper/DOI:{doi}"
        status, data, err = api_get(url, params={"fields": fields}, headers=HEADERS)
        if err:
            log.append(f"DOI lookup error: {err}")
        elif data:
            if data.get('abstract'):
                return data['abstract'], "Semantic Scholar (DOI)", log
            if data.get('tldr') and data['tldr'].get('text'):
                return "[TLDR] " + data['tldr']['text'], "Semantic Scholar (DOI, TLDR)", log
            log.append("DOI matched but search-projection had no abstract/tldr")
            if data.get('paperId'):
                time.sleep(SLEEP_SECONDS)
                result = fetch_paper_by_id(data['paperId'], log)
                if result:
                    return result, "Semantic Scholar (DOI -> full record)", log

    if title:
        match_url = "https://api.semanticscholar.org/graph/v1/paper/search/match"
        status, data, err = api_get(match_url, params={"query": title, "fields": fields}, headers=HEADERS)
        if err:
            log.append(f"/match error: {err}")
        elif data and data.get('data'):
            paper = data['data'][0]
            if paper.get('abstract'):
                return paper['abstract'], "Semantic Scholar (match)", log
            if paper.get('tldr') and paper['tldr'].get('text'):
                return "[TLDR] " + paper['tldr']['text'], "Semantic Scholar (match, TLDR)", log
            log.append("/match found paper but search-projection had no abstract/tldr")
            if paper.get('paperId'):
                time.sleep(SLEEP_SECONDS)
                result = fetch_paper_by_id(paper['paperId'], log)
                if result:
                    return result, "Semantic Scholar (match -> full record)", log
        else:
            log.append("/match returned no candidates")

        time.sleep(SLEEP_SECONDS)

        search_url = "https://api.semanticscholar.org/graph/v1/paper/search"
        status, data, err = api_get(search_url, params={"query": title, "limit": 1, "fields": fields}, headers=HEADERS)
        if err:
            log.append(f"/search error: {err}")
        elif data and data.get('data'):
            paper = data['data'][0]
            if paper.get('abstract'):
                return paper['abstract'], "Semantic Scholar (search)", log
            if paper.get('tldr') and paper['tldr'].get('text'):
                return "[TLDR] " + paper['tldr']['text'], "Semantic Scholar (search, TLDR)", log
            log.append("/search found paper but search-projection had no abstract/tldr")
            if paper.get('paperId'):
                time.sleep(SLEEP_SECONDS)
                result = fetch_paper_by_id(paper['paperId'], log)
                if result:
                    return result, "Semantic Scholar (search -> full record)", log
        else:
            log.append("/search returned no candidates")

    return None, None, log


def main():
    print(f"Loading {INPUT_FILE}...")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        bib_database = bibtexparser.load(f)

    total = len(bib_database.entries)
    print(f"Found {total} records.\n")

    updated = 0
    source_counts = {}
    needs_manual = []

    for i, entry in enumerate(bib_database.entries, 1):
        pid = entry.get('ID', 'Unknown ID')
        title = entry.get('title')
        doi = entry.get('doi')
        url_field = entry.get('url', '')

        print(f"[{i}/{total}] {pid}: {title[:70]}...")
        abstract, source, log = fetch_full_abstract(doi, title)

        if abstract:
            entry['abstract'] = abstract
            entry['abstract_source'] = source  # traceability for your SLR methodology
            updated += 1
            source_counts[source] = source_counts.get(source, 0) + 1
            print(f"   [+] Success via {source}")
        else:
            print("   [-] Failed. Reasons:")
            for line in log:
                print(f"       - {line}")
            needs_manual.append((pid, title, url_field))

        time.sleep(SLEEP_SECONDS)

    print(f"\nUpdated {updated}/{total} abstracts.")
    if source_counts:
        print("Breakdown by source:")
        for src, count in sorted(source_counts.items(), key=lambda x: -x[1]):
            print(f"   {src}: {count}")

    if needs_manual:
        print(f"\n{len(needs_manual)} entries need manual lookup (not found in any source):")
        for pid, title, url_field in needs_manual:
            print(f"   {pid}: {title}")
            if url_field:
                print(f"      {url_field}")

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        bibtexparser.dump(bib_database, f)
    print(f"Saved to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()